import type { TerminalTheme } from "../types";

export const rosePineMoon: TerminalTheme = {
  id: "rose-pine-moon",
  name: "Moon",
  group: "Rosé Pine",
  variant: "dark",
  xterm: {
    background: "#232136",
    foreground: "#e0def4",
    cursor: "#56526e",
    cursorAccent: "#e0def4",
    selectionBackground: "#44415a",
    selectionForeground: "#e0def4",
    black: "#393552",
    red: "#eb6f92",
    green: "#3e8fb0",
    yellow: "#f6c177",
    blue: "#9ccfd8",
    magenta: "#c4a7e7",
    cyan: "#ea9a97",
    white: "#e0def4",
    brightBlack: "#6e6a86",
    brightRed: "#eb6f92",
    brightGreen: "#3e8fb0",
    brightYellow: "#f6c177",
    brightBlue: "#9ccfd8",
    brightMagenta: "#c4a7e7",
    brightCyan: "#ea9a97",
    brightWhite: "#e0def4",
  },
  ui: {
    compositionBackground: "#44415a",
    compositionForeground: "#e0def4",
    compositionBorder: "#6e6a86",
    dragOverlayBackground: "rgba(35, 33, 54, 0.7)",
  },
};
