// Tauri IPC command wrappers — generated by specta (manual for now)
// Components must use these instead of calling invoke() directly

import { invoke } from "@tauri-apps/api/core";

export async function healthCheck(): Promise<string> {
  return invoke<string>("health_check");
}

// Environment
export interface DependencyStatus {
  installed: boolean;
  version: string | null;
  message: string;
  installHint: string | null;
}

export interface EnvironmentStatus {
  claudeCli: DependencyStatus;
  tmux: DependencyStatus;
  claudeAuth: DependencyStatus;
  allReady: boolean;
}

export async function checkEnvironment(): Promise<EnvironmentStatus> {
  return invoke<EnvironmentStatus>("check_environment");
}

export async function recheckEnvironment(): Promise<EnvironmentStatus> {
  return invoke<EnvironmentStatus>("recheck_environment");
}

// Project types
export interface Project {
  id: string;
  name: string;
  path: string;
  colorIndex: number;
  accountId: string | null;
  defaultPrompt: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  pathExists: boolean;
}

export interface UpdateProjectInput {
  name?: string;
  path?: string;
  accountId?: string | null;
  defaultPrompt?: string | null;
}

// Project commands
export async function createProject(
  name: string,
  path: string,
): Promise<string> {
  return invoke<string>("create_project", { name, path });
}

export async function listProjects(): Promise<Project[]> {
  return invoke<Project[]>("list_projects");
}

export async function getProject(id: string): Promise<Project | null> {
  return invoke<Project | null>("get_project", { id });
}

export async function updateProject(
  id: string,
  input: UpdateProjectInput,
): Promise<Project> {
  return invoke<Project>("update_project", { id, input });
}

export async function deleteProject(id: string): Promise<void> {
  return invoke<void>("delete_project", { id });
}

export async function restoreProject(id: string): Promise<Project> {
  return invoke<Project>("restore_project", { id });
}

export async function purgeProject(id: string): Promise<void> {
  return invoke<void>("purge_project", { id });
}
